version: '3'

services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/src/app
      - node_modules_api:/src/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  #Database
  db:
    container_name: db
    image: postgres:14.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db:
    driver: local
  node_modules_api:
